# Generated by Django 4.1.2 on 2022-11-05 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded'),
        ),
    ]
