# Generated by Django 4.1.2 on 2022-11-05 10:40

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0002_alter_correspondence_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='correspondence',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
