# Generated by Django 4.1.2 on 2022-11-05 11:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0003_correspondence_voice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='correspondence',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='videos_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
        migrations.AlterField(
            model_name='correspondence',
            name='voice',
            field=models.FileField(blank=True, null=True, upload_to='voice_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls'])]),
        ),
    ]
