# Generated by Django 4.1.2 on 2022-11-05 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0005_correspondence_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondence',
            name='city',
        ),
    ]
