# Generated by Django 4.1.2 on 2022-11-08 11:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('correspondence', '0006_remove_correspondence_city'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='correspondence',
            name='voice',
        ),
        migrations.AddField(
            model_name='correspondence',
            name='textfile',
            field=models.FileField(blank=True, null=True, upload_to='textfile_uploaded', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['.pdf', '.doc', '.docx', '.jpg', '.png', '.xlsx', '.xls'])]),
        ),
    ]
