# Generated by Django 4.1.2 on 2022-11-08 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('correspondence', '0008_groupcorrespondence'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='groupcorrespondence',
            name='groupname',
        ),
        migrations.RemoveField(
            model_name='groupcorrespondence',
            name='groupuser',
        ),
        migrations.CreateModel(
            name='Group',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('groupuser', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='groupcorrespondence',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='correspondence.group'),
            preserve_default=False,
        ),
    ]
